//
// Copyright (c) 2021 NVI, Inc.
//
// This file is part of VLBI Field System
// (see http://github.com/nvi-inc/fs).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

= DRAFT VEX parser and writer API description
E. Himwich
Version 0.3 - November 2021

:sectnums:
:toc:

== Introduction

This document provides a terse description of the VEX parser and
writer Application Program Interface (API). Whenever there is a
non-backward compatible change in the API in a released version of the
parser or writer, the first field in the version string will be
incremented.

The remaining sections of this document list the API features, a
history of non-backward compatible API changes, _discouraged_
features, and lastly _deprecated_ features.

== API

=== VEX parser

The parser API includes functions and other programming language
syntactic elements.

==== Functions

The functions in the parser API include all those that are externally
visible in the source files:

* _vex_get.c_

+

This `get_*()` functions in this file make up the bulk of the C
language parser interface. Examples of calls to these functions can be
found in the _vexf_get.c_ source file. The `find_*()` functions in
this file are also part of the API, but their use is discouraged.


* _vexf_get.c_

+

The externally visible functions in this file make up the FORTRAN
parser interface. The functions have explanations of their calling
sequences in their source. The `fget_*()` functions  are similar to the
corresponding `get_*()` C language interface functions. Many of the
`fvex_*()` functions, for example `fvex_ra()`, may also be useful in
the C language.


Additionally for the C language, one function in the _vex_util.c_
source file is part of the API:

* `vex_field()`

+

A synopsis of its calling sequence is included inline in the source.

==== C language syntactic elements

Beginning with _v2.0.0_ (released in FS _9.5.0_, September 2001), the
following C language syntactic elements became de facto parts of the
API:

* Symbolic names for the VEX parameter tokens (e.g., `T_CHAN_DEF` for
`chan_def`) and the block names (e.g., `B_FREQ` for `$FREQ`).

* Data structures for the VEX primitive statements. For some
parameters that have only a single field, there is no explicit data
structure, just a pointer to the data of that field. Direct use of
these data structures/pointers is discouraged.

* Memory linked lists that store the contents of a VEX file. Direct
use of these lists is _strongly_ discouraged.

The direct use of these discouraged syntactic elements can be avoided
by using only the `get_*()` functions from _vex_get.c_ along with
`vex_field()` from _vex_util.c_. Instead, or in addition, the
`fget_*()` functions from _vexf_get.c_ can be used. The `get_*()` and
`fget_*()` functions also enforce the context of the VEX data, e.g.,
which VEX parameters apply to which station and mode or globally.

NOTE: Prior to _v2.0.0_, the last non-backward compatible changes in
any of these syntactic elements was in _v.1.2.0_, released in FS
_9.3.6_, January, 1997. That update included the changes for VEX
_1.5_.

==== C language examples

Some examples of use of the parser in the C language are included in
the _examples_ subdirectory. There aren't many of them at this time,
but more may be added.

==== FORTRAN syntactic elements

Beginning with _v2.0.0_ (released in FS _9.5.0_, September 2001), the
character string representations of the symbolic names for the VEX
parameter tokens (e.g., `chan_def` for `T_CHAN_DEF`) and block name
tokens (e.g., `FREQ` for `B_FREQ`) became de facto parts of the API.

NOTE: Prior to _v2.0.0_, the last non-backward compatible changes in
any of these syntactic elements was in _v.1.2.0_, released in FS
_9.3.6_, January, 1997. That update included the changes for VEX
_1.5_.

=== VEX writer

The functions in the writer API include all functions in the source
files:

* _vex_put.c_ -- C language

+

These are the `create_*()` functions.

* _vexf_put.c_ -- FORTRAN

+

These are the `fcreate_*()` functions.

== Non-backward compatible API changes

=== v3

This sub-section covers the non-backward compatible feature changes in
the _v3_ API, as compared to _v2_. That transition corresponds to the
update to the VEX1-and-VEX2 capable parser from the VEX1-only capable
parser. The latter having been distributed in FS version _10.0.0_ and
earlier releases, available at https://github.com/nvi-inc/fs (some
subsequent FS releases may also contain the VEX1-only parser). All the
changes were only to direct use of the VEX parameter data
structures/pointers.

NOTE: Being backward compatible does not imply being able to support
VEX2. Please see the <<Deprecated features>> section below for details
on the changes that are needed to support VEX2 usage of VEX parameters
that existed in VEX1.

==== VEX parameter data structure changes

For all but two of the changes, a pointer to the VEX parameter data
was replaced with a pointer to a data structure. The two that are
different are `source_type` and `VEX_rev`.

The data structures for the following VEX parameters changed:

* `exper_name`

+

The storage was changed from a string value to the `exper_name`
structure.

* `site_ID`

+

The storage was changed from a string value to the `site_id`
structure.

* `source`

+

The storage was changed from a string value to the `source` structure.

* `source_type`

+

The storage was changed from a string value list to the `source_type`
structure.

* `VEX_rev`

+

The storage was changed from a `dvalue` structure to a string value.

=== v2

This sub-section covers the non-backward compatible features in the
_v2_ API, as compared to _v1.2.2_. The _v2.0.0_ version of the parser
was released in FS _9.5.0_, September 2001. All the changes were to
functions.

==== Function changes

* _vex_get.c_

+

The calling sequence for the following functions changed:

** `get_scan_station()`
** `get_scan_station_next()`

* _vexf.c_  (now _vexf_get.c_)

+

The calling sequence for the following function changed:

** `fget_scan_station()`

== Discouraged features

_Discouraged_ features are acceptable for existing code, but should
not be used in new code. Avoiding their use will insulate user code
from most internal changes in the parser. Ideally all discouraged
features should be eliminated from the API, but at this time that is
not practical. Currently, all of the discouraged features are part of
the C language parser API.

=== Functions

The following functions from _vex_get.c_ are discouraged:

* `find_block()`
* `find_def()`
* `find_lowl()`
* `find_next_def()`
* `find_next_scan()`

These are lower-level functions. It should be possible to restructure
any use of them in terms of the `get_*()` functions in _vex_get.c_.
However, if this appears to prevent some information from being
accessed properly, please contact the maintainer.

=== Data structures

Direct use of the data structures for the VEX primitive statements is
discouraged. Not using them will shield user code from changes in the
data structures. The `vex_field()` function from _vex_util.c_ should
be used instead.

Direct use of the memory linked list of the VEX file data is
_strongly_ discouraged. Avoiding this will shield user code from
changes in linked list structure. The `get_*()` functions in
_vex_get.c_ should be used instead.

== Deprecated features

_Deprecated_ features should be removed and replaced with updated
features. Typically, this is needed because the functionality of the
deprecated feature is too limited for use with VEX2. They will still
work for VEX1 functionality. The deprecated features may be removed
some day. Currently, the only deprecated features are functions.

NOTE: The replacement functions are not plug replacements for the
deprecated ones. The returned values and/or calling sequences have
changed.

=== C language

==== vex_get.c

The following functions from _vex_get.c_ are deprecated:

* `get_scan_source()`
* `get_scan_source_next()`

Use of those functions should be replaced with, respectively:

IMPORTANT: The returned values of the replacement functions are
different.

* `get_scan_source2()`
* `get_scan_source2_next()`

==== vex_put.c

The following functions from _vex_put.c_ are deprecated:

* `create_antenna_motion()`
* `create_axis_type()`
* `create_chan_def()`
* `create_chan_def_states()`
* `create_clock()`
* `create_clock_early()`
* `create_exper_name()`
* `create_if_def()`
* `create_pointing_sector()`
* `create_site_ID()`
* `create_source()`
* `create_source_type()`
* `create_vsn()`

Use of those functions should be replaced with, respectively:

IMPORTANT: The calling sequences of the replacement functions are
different.

* `create_antenna_motion2()`
* `create_axis_type2()`
* `create_chan_def2()`
* `create_chan_def2_states()`
* `create_clock_early2()`
* `create_clock_early2()`
* `create_exper_name2()`
* `create_if_def2()`
* `create_pointing_sector2()`
* `create_site_ID2()`
* `create_source2()`
* `create_source_type2()`
* `create_vsn2()`

=== FORTRAN

==== vexf_get.c

The following function from _vexf_get.c_ is deprecated:

* `fvex_scan_source()`

Use of that function should be replaced with:

IMPORTANT: The calling sequence of the replacement function is
different.

CAUTION: There is a change from `fvex_...()`  to `fget_...()`. The
deprecated function was inconsistently named.

* `fget_scan_source2()`

==== vexf_put.c

The following functions from _vexf_put.c_ are deprecated:

* `fcreate_antenna_motion()`
* `fcreate_axis_type()`
* `fcreate_chan_def()`
* `fcreate_chan_def_states()`
* `fcreate_clock()`
* `fcreate_clock_early()`
* `fcreate_exper_name()`
* `fcreate_if_def()`
* `fcreate_pointing_sector()`
* `fcreate_site_ID()`
* `fcreate_source()`
* `fcreate_source_type()`
* `fcreate_vsn()`

Use of those functions should be replaced with, respectively:

IMPORTANT: The calling sequences of the replacement functions are
different.

* `fcreate_antenna_motion2()`
* `fcreate_axis_type2()`
* `fcreate_chan_def2()`
* `fcreate_chan_def2_states()`
* `fcreate_clock_early2()`
* `fcreate_clock_early2()`
* `fcreate_exper_name2()`
* `fcreate_if_def2()`
* `fcreate_pointing_sector2()`
* `fcreate_site_ID2()`
* `fcreate_source2()`
* `fcreate_source_type2()`
* `fcreate_vsn2()`
